name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  testsuite:
    env:
      PERL_USE_UNSAFE_INC: 1
      CPANEL_BIN_PATH: /usr/local/cpanel/3rdparty/bin
      CPANEL_PERL: /usr/local/cpanel/3rdparty/perl/532/bin/perl

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: cpanelos/perl-compiler:perl-v5.32.0
      #options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PATH
        run: |
          echo $CPANEL_BIN_PATH >> $GITHUB_PATH;
          $CPANEL_PERL -MConfig -E 'say $Config{sitebin}' >> $GITHUB_PATH
          $CPANEL_PERL -MConfig -E 'say $Config{vendorbin}' >> $GITHUB_PATH
      - run: perl -V
      - name: install Perl dependencies
        uses: perl-actions/install-with-cpm@stable
        with:
          sudo: false
          cpanfile: "t/cpanfile"
          args: "--with-all"
      - name: cpanel-setup
        run: /bin/bash t/cpanel-setup
      - name: which prove
        run: ls -l $(which prove)
      - run: perl -cw elevate-cpanel
      - name: Run tests
        run: prove -l -It/lib t/*.t
      - name: (Re)install Perl dependencies
        uses: perl-actions/install-with-cpm@stable
        with:
          sudo: false
          cpanfile: "t/cpanfile"
          args: "--with-all"
      - name: Code coverage
        run: |
          make cover
          cp cover_db/elevate-cpanel.html cover_db/index.html
          rm -rf cover_db/runs cover_db/structure cover_db/digests
          tar cvzf cover_db.tar.gz cover_db
      - name: Archive code coverage
        uses: actions/upload-artifact@v2
        with:
          name: cover_db.tar.gz
          path: cover_db.tar.gz
          retention-days: 21

