name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  testsuite:
    env:
      PERL_USE_UNSAFE_INC: 1
      CPANEL_BIN_PATH: /usr/local/cpanel/3rdparty/bin
      CPANEL_PERL_BIN_PATH: /usr/local/cpanel/3rdparty/perl/532/bin

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: cpanelos/perl-compiler:perl-v5.32.0
      #options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PATH
        run: |
          echo $CPANEL_BIN_PATH >> $GITHUB_PATH;
          echo $CPANEL_PERL_BIN_PATH >> $GITHUB_PATH
      - run: perl -V
      - name: which perl
        run: ls -l $(which perl)
      - name: fixup for Test-MockFile
        uses: perl-actions/install-with-cpm@stable
        with:
          sudo: false
          install: |
              http://httpupdate.cpanel.net/CPAN/authors/id/T/TO/TODDR/Test-MockFile-0.025.tar.gz
      - name: install Perl dependencies
        uses: perl-actions/install-with-cpm@stable
        with:
          sudo: false
          cpanfile: "t/cpanfile"
          args: "--with-recommends --with-suggests"
      - name: cpanel-setup
        run: /bin/bash t/cpanel-setup
      - name: which prove
        run: ls -l $(which prove)
      - run: perl -cw elevate-cpanel
      - name: Run tests
        run: prove -l -It/lib t/*.t
